apiVersion: v1
kind: Service
metadata:
  name: mywebapp
  labels:
    run: mywebapp
spec:
  type: LoadBalancer
  ports:
  - port: "8080:80"
    targetPort: 
    protocol: TCP
    name: http
  selector:
    run: mywebapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mywebapp
spec:
  replicas: 3        
  selector:
    matchLabels:
      run: mywebapp
  template:
    metadata:
      labels:
        run: mywebapp
    spec:
      containers:
      - name: mysql
        image: mysql
        env:      
	  - MYSQL_ROOT_PASSWORD=password
      	  - MYSQL_DATABASE=myDB
        - name:  
          value: 
        ports:
        - containerPort: 3306  
      - name: webapp
        image: part-3-image           
        ports:
        - containerPort: 8080