version: "3.3"

services: 
  app-db: 
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: myDB

  app:
    build: ./tomcat
    ports:
      - "8080:8080"
    depends_on: 
      - app-db
    